spring.application.name=LiterAlura
spring.datasource.url=jdbc:postgresql://${DB_Host}/${DB_Nombre}
#spring.datasource.url=jdbc:postgresql://localhost:5432/liter_alura
spring.datasource.username=${DB_User}
spring.datasource.password=${DB_contrasena}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA (opcional: actualizar, crear o validar el esquema)
spring.jpa.hibernate.ddl-auto=update

# Mostrar consultas SQL en consola (opcional)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#logging.level.org.springframework=DEBUG
